# Generated by Django 5.2.8 on 2025-12-10 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
        ("tasks", "0004_task_tasks_task_status_4a0a95_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["task"], name="comments_co_task_id_54a67f_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author"], name="comments_co_author__4d2625_idx"
            ),
        ),
    ]
