import { Notification } from "@/lib/types";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

interface ActivitySectionProps {
  notifications: Notification[];
  onMarkAllRead?: () => void;
}

export const ActivitySection = ({ notifications, onMarkAllRead }: ActivitySectionProps) => (
  <Card id="activity">
    <CardHeader className="flex flex-row items-center justify-between">
      <div>
        <CardTitle>Notifications</CardTitle>
        <CardDescription>Latest updates generated by tasks, comments, or projects.</CardDescription>
      </div>
      {notifications.length > 0 && (
        <Button variant="ghost" size="sm" onClick={onMarkAllRead}>
          Mark all read
        </Button>
      )}
    </CardHeader>
    <CardContent className="space-y-4">
      {notifications.length === 0 && <p className="text-sm text-zinc-500">Inbox zero. 🎉</p>}
      {notifications.map((notification) => (
        <div key={notification.id} className="rounded-2xl border border-zinc-100 p-4 dark:border-zinc-800">
          <div className="flex items-center justify-between">
            <p className="text-base font-semibold text-zinc-900 dark:text-zinc-50">{notification.title}</p>
            {!notification.is_read && <span className="text-xs font-semibold text-emerald-600">New</span>}
          </div>
          <p className="mt-1 text-sm text-zinc-600 dark:text-zinc-300">{notification.message}</p>
          <p className="mt-2 text-xs text-zinc-400">
            {new Date(notification.created_at).toLocaleString(undefined, { hour: "2-digit", minute: "2-digit", hour12: true })}
          </p>
        </div>
      ))}
    </CardContent>
  </Card>
);
