# Generated by Django 5.2.8 on 2025-12-10 17:18

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_blocked_by_task_completed_at_task_started_at"),
    ]

    operations = [
        TrigramExtension(),
    ]
